### ISSUE TITLE
Things to do before you leave

### ISSUE THREAD

**Issue by alecive** [HIRO-group/openface_ros#1]
Hey @Azurisky , great work!! Here are a couple things I'd like you to do before you wrap things up for the semester:

 * Things to do to the `README.md` file: 
    * Add a description of what this repository is about, and a description of the various parts. For example, what is in the `meshes` folder? How is it used? And so on. Try to put links and references for things that you are using [for example, reference to the openface repo] 
    * Add a description of the libraries, and how they play together. For example, what is the difference between `openface_realsense` and `openface_ros`?
    * Add a section with dependencies and references [e.g. I see that in the launch file you call `realsense2_camera` but it is not written anywhere that it is supposed to be downloaded and built] 
 * Cleanup `CMakeLists.txt` [there are a lot of comments in the beginning that can go away]
 * Finalize `package.xml` : add yourself as author, maybe @Sayter99 as maintainer [with correct emails], bump the version to at least 0.0.1, add [https://hiro-group.ronc.one](https://hiro-group.ronc.one) as website
 * Add license to both the repository and `package.xml`. This is up to you, but if you don't know what to choose, use `LGPLv2.1`
 * When all of this is done, which shouldn't take more than an hour, it would be nice to take the content of the `README.md` file and publish an article [on our wiki](https://hiro-group.ronc.one/wiki.html). I will open a separate issue with instructions on how to do it!!
 * It would be great to have a short video of your stuff working!! And a screenshot 😎 

Also, I am going to open other issues, but they are meant for @Sayter99 as initial projects for undergrads.

**Comment by Azurisky** [comment]
I already add a readme page with more details. Could you please check that and close this issue? If that looks good to you, I'll upload that to our lab web page soon! Thanks.

**Comment by alecive** [comment]
That's great, thanks @Azurisky [and @Sayter99 ]!!
