### ISSUE TITLE
using rosbag File

### ISSUE THREAD

**Issue by HAMMADIPRO** [HIRO-group/openface_ros#10]
![Screenshot from 2020-07-31 12-49-37](https://user-images.githubusercontent.com/42253715/89057855-56698880-d32c-11ea-9031-3ed3c121b967.png)
Camera Model D415
OS : Ubuntu 18.04.4
Ros distro: Melodic

When running  **rosrun openface_ros openface_realsense**  with a bagfile in Input It worked but don't give  any **_output_** 

 `rosrun openface_ros openface_realsense
Could not find the HAAR face detector location
Reading the landmark detector/tracker from: /usr/local/etc/OpenFace/model/main_ceclm_general.txt
Reading the landmark detector module from: /usr/local/etc/OpenFace/model/cen_general.txt
Reading the PDM module from: /usr/local/etc/OpenFace/model/pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: /usr/local/etc/OpenFace/model/tris_68.txt....Done
Reading the intensity CEN patch experts from: /usr/local/etc/OpenFace/model/patch_experts/cen_patches_0.25_of.dat....Done
Reading the intensity CEN patch experts from: /usr/local/etc/OpenFace/model/patch_experts/cen_patches_0.35_of.dat....Done
Reading the intensity CEN patch experts from: /usr/local/etc/OpenFace/model/patch_experts/cen_patches_0.50_of.dat....Done
Reading the intensity CEN patch experts from: /usr/local/etc/OpenFace/model/patch_experts/cen_patches_1.00_of.dat....Done
Reading part based module....left_eye_28
Reading the landmark detector/tracker from: /usr/local/etc/OpenFace/model/model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: /usr/local/etc/OpenFace/model/model_eye/clnf_left_synth.txt
Reading the PDM module from: /usr/local/etc/OpenFace/model/model_eye/pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: /usr/local/etc/OpenFace/model/model_eye/patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: /usr/local/etc/OpenFace/model/model_eye/patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Could not find the HAAR face detector location
Done
Reading part based module....right_eye_28
Reading the landmark detector/tracker from: /usr/local/etc/OpenFace/model/model_eye/main_clnf_synth_right.txt
Reading the landmark detector module from: /usr/local/etc/OpenFace/model/model_eye/clnf_right_synth.txt
Reading the PDM module from: /usr/local/etc/OpenFace/model/model_eye/pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: /usr/local/etc/OpenFace/model/model_eye/patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: /usr/local/etc/OpenFace/model/model_eye/patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Could not find the HAAR face detector location
Done
Reading the landmark validation module....Done
Reading the AU analysis module from: /usr/local/etc/OpenFace/AU_predictors/main_dynamic_svms.txt
Reading the AU predictors from: /usr/local/etc/OpenFace/AU_predictors/AU_all_best.txt... Done
Reading the PDM from: /usr/local/etc/OpenFace/AU_predictors/In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:/usr/local/etc/OpenFace/AU_predictors/tris_68_full.txt... Done
`

Would help me !

**Comment by peasant98** [comment]
Forgot, but I can close this, right @HAMMADIPRO ?

**Comment by HAMMADIPRO** [comment]
Thank you @peasant98 it's helpful. You can close this issue.
