### ISSUE TITLE
Add page to wiki

### ISSUE THREAD

**Issue by alecive** [HIRO-group/openface_ros#4]
When the `README.md` is ready and finalized, I'd like to publish its content on the website too.

@Azurisky here's how to do it:

 * Fork https://github.com/HIRO-group/HIRO-group.github.io
 * Create a new file under `_posts/wiki`, with name in the format `date-title.md` [e.g. `2019-05-06-Openface-ROS.md`]
 * Taking inspiration from [this file](https://raw.githubusercontent.com/HIRO-group/HIRO-group.github.io/master/_posts/wiki/2019-03-07-new-HIRO-member.md), you need a front matter with `title` `description` `tags` and `author`
 * After the end of the front matter, copy-paste the content of the readme file.

I understand it is quite complicated, so please feel free to ask questions if this is not clear!!!

**Comment by Azurisky** [comment]
I already add a readme page with more details. Could you please check that and close this issue? Thanks.
