### ISSUE TITLE
Openface Version

### ISSUE THREAD

**Issue by HAMMADIPRO** [HIRO-group/openface_ros#7]
Hi,
When I clone this project and build it with catkin_make  it returns me error "fatal error: stdafx_fa.h: No such file or directory compilation terminated." 
Can any one give me a solution for this problem? if I must downgrade the version of Openface or what? if that the solution I like to know which version is more compatible with openface_ros ?
 Would help me . 
![error-Openface-ros](https://user-images.githubusercontent.com/42253715/83342200-590f1980-a2ba-11ea-8808-3b17dd2a8072.png)

Best regards!

**Comment by peasant98** [comment]
Hi @HAMMADIPRO , is the issue related to https://stackoverflow.com/questions/22621928/fatal-error-stdafx-h-file-not-found? The header file names are a bit different, but maybe check it out.

**Comment by HAMMADIPRO** [comment]
> Hi @HAMMADIPRO , is the issue related to https://stackoverflow.com/questions/22621928/fatal-error-stdafx-h-file-not-found? The header file names are a bit different, but maybe check it out.

in this issue it recommended to Remove "#include  stdafx_fa.h", so it will create an error!

**Comment by peasant98** [comment]
@HAMMADIPRO it says that the header is specific to Visual Studio, and as such, isn't needed. Do you get an error when you remove the line?

**Comment by HAMMADIPRO** [comment]
I downgrade my Openface Version to [https://github.com/TadasBaltrusaitis/OpenFace/releases/tag/OpenFace_2.1.0](OpenFace_2.1.0)  and I have this error !
![screen2](https://user-images.githubusercontent.com/42253715/83343480-e6f20100-a2c8-11ea-9c13-e2dd253fb7aa.png)

**Comment by Sayter99** [comment]
@HAMMADIPRO do you install dlib 19.13 which is required by OpenFace?

I updated the header files to match the latest OpenFace repo. You could try 54e2628ba43b6b81d85053ae080e9e76f195d95d for the **latest** OpenFace, but be sure that your dependencies are correct. (dlib 19.13, opencv 4.1, etc)

@peasant98 the `stdafx_fa.h` here is provided by OpenFace repo, not the Microsoft one. So it needs to be included.

**Comment by peasant98** [comment]
@Sayter99 , ah, thanks for the clarification.

**Comment by Sayter99** [comment]
@HAMMADIPRO any updates?
