### ISSUE TITLE
smaller size face detection 

### ISSUE THREAD

**Issue by ymohamed08** [HIRO-group/openface_ros#9]
i have created my own video dataset, i get the message ``` Face is too small for landmark detection``` is there a way to make it able to detect smaller size faces ?

**Comment by peasant98** [comment]
Hi @youssef266, this seems to be an openface related issue, as our code is simply a ROS wrapper for it. Maybe consider posting an issue there, or changing the image size?

**Comment by ymohamed08** [comment]
thank you i will
